version: '3.3'
services:
  web:
    container_name: odoo18
    build: 
      context: .
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    image: 072726364414.dkr.ecr.sa-east-1.amazonaws.com/odoo/demo-website:latest
    user: "100:101"
    ports:
      - "80:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /mnt/efs:/mnt/efs
      - ./custom_addons:/opt/odoo/custom_addons
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - HOST_DB=${DB_HOST}
      - PORT_DB=${DB_PORT}
      - USER_DB=${DB_USER}
      - PASS_DB=${DB_PASSWORD}
      - NAME_DB=${DB_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: ["--database", "${NAME_DB}"]
    networks:
      - default
    restart: always

volumes:
  odoo-web-data:
    driver: local

networks:
  default: